import React, { Component } from 'react';
import { StyleSheet, Text, View, ScrollView, ImageBackground, Dimensions, StatusBar, FlatList } from 'react-native';
import { Image as ReactImage } from 'react-native';
import { TouchableOpacity } from 'react-native-gesture-handler';
import Svg, { } from 'react-native-svg';
import { Path as SvgPath } from 'react-native-svg';
import ArticleListItem from '../components/artlicle_list_item'

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default class Articlelist extends Component {

  constructor(props) {
    super(props);
    this.state = {

    };
  }


  render() {
    console.log("render articles")
    return (
      <View data-layer="c8b81245-3906-4187-abb0-1621eff4c360" style={styles.articlelist}>
        <ImageBackground data-layer="e71fa9e2-5bb1-4161-8b7e-85a365aa0607" source={require('../assets/maskGroup3.png')} style={styles.articlelist_maskGroup3} />
        <ReactImage data-layer="f8b8d495-3749-44fb-a45f-1fd7c6a46afe" source={require('../assets/menu.png')} style={styles.articlelist_menu} />
        <ReactImage data-layer="598fcfda-0feb-4ed1-bb13-4ed9c387729f" source={require('../assets/wallet.png')} style={styles.articlelist_wallet} />
        <Text data-layer="758b1726-8ad4-4b0c-aab7-a4d10cbb7a33" style={styles.articlelist_username}>AnonymousA</Text>
        <Text data-layer="a2d36fd9-cc22-4e23-8208-a96aa493d301" style={styles.articlelist_hometip}>See what other whistle blowers
have written</Text>
        <Text data-layer="0fbaf31b-9ae5-4545-b714-709233d2e0e9" style={styles.articlelist_filter}>RECENTS</Text>

        <FlatList
          data={[
            { name: "AnonymousA" },
            { name: "AnonymousB" },
            { name: "AnonymousC" },
            { name: "AnonymousD" },
            { name: "AnonymousE" },
            { name: "AnonymousF" },
            { name: "AnonymousG" },
            { name: "AnonymousH" },
            { name: "AnonymousI" },
            { name: "AnonymousJ" },
            { name: "AnonymousK" },
            { name: "AnonymousL" },
            { name: "AnonymousM" },
            { name: "AnonymousN" },
            { name: "AnonymousO" },
            { name: "AnonymousP" },
            { name: "AnonymousQ" },
            { name: "AnonymousR" },
            { name: "AnonymousS" },
            { name: "AnonymousT" },
            { name: "AnonymousU" },
            { name: "AnonymousV" },
            { name: "AnonymousW" },
            { name: "AnonymousY" },
            { name: "AnonymousZ" }
          ]}

          renderItem={(item) => <ArticleListItem data={item} />}
          keyExtractor={item => item.name}
          contentContainerStyle={{
            flexGrow: 1,
          }}

          style = {{flex : 1,paddingBottom:300}}
          nestedScrollEnabled = {false}

        />

      </View>
    );
  }
}

Articlelist.propTypes = {

}

Articlelist.defaultProps = {

}


const styles = StyleSheet.create({
  "articlelist": {
    "opacity": 1,
    "position": "relative",
    "backgroundColor": "rgba(248, 248, 248, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": windowWidth,
    "height": windowHeight,
    "left": 0,
    "top": 0,
    "right": 0,
    "bottom": 0,
    flex:1
  },

  "articlelist_maskGroup3": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": windowWidth,
    "height": windowHeight,
    "left": 0,
    "top": 0,
    "right": 0,
    "bottom": 0
  },
  "articlelist_maskGroup3_path4": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 495.72,
    "height": 208.12,
    "left": 130.1,
    "top": -0.18
  },
  "articlelist_maskGroup3_rectangle10": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 400,
    "height": 800,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": "auto",
    "height": 857,
    "left": -9,
    "top": 251,
    "right": 0
  },
  "articlelist_repeatGrid1_post959e7595": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 10,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": windowWidth,
    "height": 'auto',
    // "left": 9,
    // "top": 6
  },
  "articlelist_repeatGrid1_post959e7595_postbackground7f4d02e0": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 6,
    // "width": 'auto',
    // "height": 'auto',
    // "left": 0,
    // "top": 0
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73": {
    "opacity": 1,
    // "position": "absolute",
    margin: 20,
    "width": 42,
    "height": 42,
    alignSelf: 'flex-start'
    // "left": 22,
    // "top": 27

  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_ellipse33c2de486": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 42,
    "height": 42,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_hacker": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 25.43,
    "left": 7.35,
    "top": 8.71
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_hacker_path18": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 4.77,
    "left": 0,
    "top": 9.99
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_hacker_path19": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 9.63,
    "left": 0,
    "top": 15.79
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_hacker_path20": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 18.55,
    "height": 4.47,
    "left": 4.29,
    "top": 0
  },
  "articlelist_repeatGrid1_post959e7595_postusericon7653ed73_hacker_path21": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20.85,
    "height": 2.34,
    "left": 3.14,
    "top": 6.06
  },
  "articlelist_repeatGrid1_post959e7595_postusernamec0ba6d22": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    // "width": 106,
    // "height": 23,
    // "left": 74,
    // "top": 24
  },
  "articlelist_repeatGrid1_post959e7595_posttime0ad57fbf": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 17,
    // "left": 198,
    // "top": 28
  },
  "articlelist_repeatGrid1_post959e7595_dividerdb0681eb": {
    "opacity": 1,
    // "position": "absolute",
    margin: 10,
    "width": 3,
    "height": 3,
    // "left": 187,
    // "top": 35
  },
  "articlelist_repeatGrid1_post959e7595_postdate9f991d34": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 78,
    "height": 17,
    // "left": 74,
    // "top": 56
  },
  "articlelist_repeatGrid1_post959e7595_postmoney58bf9a29": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 27.5,
    "height": 30.5,
    "right": 20,
    "top": 20
  },
  "articlelist_repeatGrid1_post959e7595_postmoney58bf9a29_ellipse564d63a98": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 3,
    "width": 20,
    "height": 23,
    "left": 0,
    "top": 6
  },
  "articlelist_repeatGrid1_post959e7595_postmoney58bf9a29_ellipse62b8fe6d9": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 17,
    "height": 17,
    "left": 6,
    "top": 0
  },
  "articlelist_repeatGrid1_post959e7595_postshort2bafe453": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(136, 136, 136, 1)",
    "fontSize": 17,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "width": 250,
    marginTop: 10,
    marginEnd: 10,
    height: 'auto',
    flexWrap: 'wrap'
    // "height": 103,
    // "left": 74,
    // "top": 113
  },
  "articlelist_repeatGrid1_post959e7595_viewmoref7978898": {
    "opacity": 1,
    // "position": "relative",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(252, 142, 142, 1)",
    "fontSize": 17,
    marginTop: 10,
    marginEnd: 40,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "right",
    "width": 'auto',
    alignSelf: 'stretch'
    // "top": 224
  },
  "articlelist_repeatGrid1_post291d0fba": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 400,
    "height": 268,
    "left": 9,
    "top": 292
  },
  "articlelist_repeatGrid1_post291d0fba_postbackgroundb4314862": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 6,
    "width": 400,
    "height": 268,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 42,
    "height": 42,
    "left": 22,
    "top": 27
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_ellipse38d37b826": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 42,
    "height": 42,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_hacker44f43b32": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 25.43,
    "left": 7.35,
    "top": 8.71
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_hacker44f43b32_path18c209c9d0": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 4.77,
    "left": 0,
    "top": 9.99
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_hacker44f43b32_path19ed8b8a96": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 9.63,
    "left": 0,
    "top": 15.79
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_hacker44f43b32_path20b1346883": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 18.55,
    "height": 4.47,
    "left": 4.29,
    "top": 0
  },
  "articlelist_repeatGrid1_post291d0fba_postusericon45a921f3_hacker44f43b32_path21c3cde473": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20.85,
    "height": 2.34,
    "left": 3.14,
    "top": 6.06
  },
  "articlelist_repeatGrid1_post291d0fba_postusername0d94049c": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 106,
    "height": 23,
    "left": 74,
    "top": 24
  },
  "articlelist_repeatGrid1_post291d0fba_posttime18b8b105": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 17,
    "left": 198,
    "top": 28
  },
  "articlelist_repeatGrid1_post291d0fba_dividere6133ebf": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 3,
    "height": 3,
    "left": 187,
    "top": 35
  },
  "articlelist_repeatGrid1_post291d0fba_postdate03f30597": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 78,
    "height": 17,
    "left": 74,
    "top": 56
  },
  "articlelist_repeatGrid1_post291d0fba_postmoney6d49d7f8": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 27.5,
    "height": 30.5,
    "left": 347.5,
    "top": 39
  },
  "articlelist_repeatGrid1_post291d0fba_postmoney6d49d7f8_ellipse5969b76ec": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 3,
    "width": 20,
    "height": 23,
    "left": 0,
    "top": 6
  },
  "articlelist_repeatGrid1_post291d0fba_postmoney6d49d7f8_ellipse624998597": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 17,
    "height": 17,
    "left": 6,
    "top": 0
  },
  "articlelist_repeatGrid1_post291d0fba_postshort6c7ef4b5": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(136, 136, 136, 1)",
    "fontSize": 17,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 316,
    "height": 103,
    "left": 74,
    "top": 113
  },
  "articlelist_repeatGrid1_post291d0fba_viewmoree3e746ad": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(252, 142, 142, 1)",
    "fontSize": 17,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 87,
    "height": 24,
    "left": 288,
    "top": 224
  },
  "articlelist_repeatGrid1_post": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 400,
    "height": 268,
    "left": 9,
    "top": 578
  },
  "articlelist_repeatGrid1_post_postbackground": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 6,
    "width": 400,
    "height": 268,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1_post_postusericon": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 42,
    "height": 42,
    "left": 22,
    "top": 27
  },
  "articlelist_repeatGrid1_post_postusericon_ellipse3": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 42,
    "height": 42,
    "left": 0,
    "top": 0
  },
  "articlelist_repeatGrid1_post_postusericon_hackerb66f5a22": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 25.43,
    "left": 7.35,
    "top": 8.71
  },
  "articlelist_repeatGrid1_post_postusericon_hackerb66f5a22_path1845489a0b": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 4.77,
    "left": 0,
    "top": 9.99
  },
  "articlelist_repeatGrid1_post_postusericon_hackerb66f5a22_path19f68299ae": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 27.12,
    "height": 9.63,
    "left": 0,
    "top": 15.79
  },
  "articlelist_repeatGrid1_post_postusericon_hackerb66f5a22_path20abc8e11b": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 18.55,
    "height": 4.47,
    "left": 4.29,
    "top": 0
  },
  "articlelist_repeatGrid1_post_postusericon_hackerb66f5a22_path2183f9d74a": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 20.85,
    "height": 2.34,
    "left": 3.14,
    "top": 6.06
  },
  "articlelist_repeatGrid1_post_postusername": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 16,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 106,
    "height": 23,
    "left": 74,
    "top": 24
  },
  "articlelist_repeatGrid1_post_posttime": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 48,
    "height": 17,
    "left": 198,
    "top": 28
  },
  "articlelist_repeatGrid1_post_divider": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 3,
    "height": 3,
    "left": 187,
    "top": 35
  },
  "articlelist_repeatGrid1_post_postdate": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(100, 100, 100, 1)",
    "fontSize": 12,
    "fontWeight": "300",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 78,
    "height": 17,
    "left": 74,
    "top": 56
  },
  "articlelist_repeatGrid1_post_postmoney": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 27.5,
    "height": 30.5,
    "left": 347.5,
    "top": 39
  },
  "articlelist_repeatGrid1_post_postmoney_ellipse5": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "shadowColor": "rgb(0,  0,  0)",
    "shadowOpacity": 0.1607843137254902,
    "shadowOffset": {
      "width": 0,
      "height": 3
    },
    "shadowRadius": 3,
    "width": 20,
    "height": 23,
    "left": 0,
    "top": 6
  },
  "articlelist_repeatGrid1_post_postmoney_ellipse6": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 17,
    "height": 17,
    "left": 6,
    "top": 0
  },
  "articlelist_repeatGrid1_post_postshort": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(136, 136, 136, 1)",
    "fontSize": 17,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 316,
    "height": 103,
    "left": 74,
    "top": 113
  },
  "articlelist_repeatGrid1_post_viewmore": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(252, 142, 142, 1)",
    "fontSize": 17,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 87,
    "height": 24,
    "left": 288,
    "top": 224
  },
  "articlelist_username": {
    "opacity": 1,
    "position": 'relative',
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(112, 112, 112, 1)",
    "fontSize": 28,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "width": 187,
    "height": 39,
    marginTop: 100,
    marginStart: 20
    // "left": 22,
    // "top": 63
  },
  "articlelist_menu": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 10,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 24,
    "height": 17,
    "left": 22,
    "top": StatusBar.currentHeight
  },
  "articlelist_menu_rectangle5": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(112, 112, 112, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 24,
    "height": 3,
    "left": 0,
    "top": 0
  },
  "articlelist_menu_rectangle6": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(112, 112, 112, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 13,
    "height": 3,
    "left": 0,
    "top": 7
  },
  "articlelist_menu_rectangle7": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(112, 112, 112, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 21,
    "height": 3,
    "left": 0,
    "top": 14
  },
  "articlelist_hometip": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(112, 112, 112, 0.7294117647058823)",
    "fontSize": 16,
    "fontWeight": "500",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 10,
    "marginRight": 20,
    "marginBottom": 0,
    "marginLeft": 20,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 248,
    "height": 48,
    // "left": 22,
    // "top": 106
  },
  "articlelist_filter": {
    "opacity": 1,
    // "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(112, 112, 112, 1)",
    "fontSize": 16,
    "fontWeight": "500",
    "fontStyle": "normal",
    "fontFamily": "Roboto",
    "textAlign": "left",
    "marginTop": 10,
    "marginRight": 0,
    "marginBottom": 10,
    "marginLeft": 20,
    // "width": 69,
    // "height": 23,
    // "left": 22,
    // "top": 185
  },
  "articlelist_wallet": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 10,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 29.25,
    "height": 27,
    "right": 20.74,
    "top": StatusBar.currentHeight
  },
  "articlelist_wallet_path26": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 29.25,
    "height": 20.25,
    "left": 0,
    "top": 6.75
  },
  "articlelist_wallet_path27": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 23.63,
    "height": 6.4,
    "left": 1.13,
    "top": 0
  }
});