import {StyleSheet} from 'react-native';
import {colors} from "./colors"



export const styles1 = StyleSheet.create({

    container : {
        backgroundColor : '#f8f8f8'
    },
    main_title : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 61,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    main_description : {
        color: '#707070',
        fontFamily: 'Roboto',
        fontSize: 24,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    red_button : {
        shadowColor: 'rgba(0, 0, 0, 0.16)',
        shadowOffset: { width: 2, height: 0 },
        shadowRadius: 6,
        borderRadius: 10,
        backgroundColor: '#e63950',
    },
    red_button_text : {
        color: 'rgba(255, 255, 255, 0.9)',
        fontFamily: 'Roboto',
        fontSize: 20,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_card : {
        shadowColor: 'rgba(0, 0, 0, 0.16)',
        shadowOffset: { width: 3, height: 0 },
        shadowRadius: 6,
        backgroundColor: '#ffffff',
    },
    post_card_text : {
        color: '#888888',
        fontFamily: 'Myanmar Text',
        fontSize: 17,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_card_user_text : {
        color: '#646464',
        fontFamily: 'Poppins',
        fontSize: 16,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_card_date_time_text : {
        color: '#646464',
        fontFamily: 'Poppins',
        fontSize: 12,
        fontWeight: '300',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_card_text_button : {
        color: '#fc8e8e',
        fontFamily: 'Poppins',
        fontSize: 17,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    page_title : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 28,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    page_description : {
        color: 'rgba(112, 112, 112, 0.73)',
        fontFamily: 'Poppins',
        fontSize: 16,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    /**
     * RECENT , HISTORY
     */
    page_filter : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 16,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_title : {
        color: '#505050',
        fontFamily: 'Poppins',
        fontSize: 39,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    post_content : {
        color: '#888888',
        fontFamily: 'Myanmar Text',
        fontSize: 16,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    toolbar_text : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 28,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    hint_large : {
        color: 'rgba(112, 112, 112, 0.45)',
        fontFamily: 'Poppins',
        fontSize: 28,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    wallet_card : {
        shadowColor: 'rgba(0, 0, 0, 0.03)',
        shadowOffset: { width: 0, height: 0 },
        shadowRadius: 15,
        borderRadius: 15,
        backgroundColor: '#ffffff',
    },
    wallet_label_text : {
        color: 'rgba(112, 112, 112, 0.67)',
        fontFamily: 'Poppins',
        fontSize: 21,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    wallet_text_large : {
        color: '#f17c8c',
        fontFamily: 'Poppins',
        fontSize: 56,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 2.41,
        lineHeight: 'normal',
    },
    wallet_text_medium : {
        color: '#f17c8c',
        fontFamily: 'Poppins',
        fontSize: 23,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 0.99,
        lineHeight: 'normal',
    },
    profile_label : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 20,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    profile_text : {
        color: 'rgba(112, 112, 112, 0.67)',
        fontFamily: 'Poppins',
        fontSize: 40,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    },
    profile_light_text : {
        color: '#707070',
        fontFamily: 'Poppins',
        fontSize: 20,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        letterSpacing: 'normal',
        lineHeight: 'normal',
    }
})